dist: trusty
os: linux
language: cpp
compiler: gcc

notifications:
  email: false

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    - ENABLE_COVERAGE=true
    - CODECOV_TOKEN="ec1cf399-75c2-4c64-9130-c49a2ad084fe"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
      - cmake
      - lcov

before_install:
  - sudo apt-get update
  - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
  - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}

install:
  # Download and install recent cmake
  - |
    if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
      CMAKE_URL="http://cmake.org/files/v3.16/cmake-3.16.0-Linux-x86_64.tar.gz"
      mkdir -p ${DEPS_DIR}/cmake
      travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi
  - sudo apt-get update

  # Manually installs LCOV 1.14
  - wget -c http://downloads.sourceforge.net/ltp/lcov-1.14.tar.gz
  - tar -xf lcov-1.14.tar.gz
  - cd lcov-1.14
  - sudo make install
  - cd

  - lcov --version
  - gcov --version

before_script:
  - export CC=/usr/bin/gcc-9
  - export CXX=/usr/bin/g++-9

  - gcc -v
  - g++ -v
  - cmake --version

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build
  - cd build
  - cmake ${CMAKE_OPTIONS} --DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - cd test
  - ./teststep
#  - ctest

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info --gcov-tool gcov-9
  - lcov --remove coverage.info '*/test/*' '*/lib/*' '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports"